default: &default
  adapter: postgresql

development:
  <<: *default
  database: adhesion_development

test:
  <<: *default
  database: adhesion_test

production:
  <<: *default
  database: adhesion_production
